{% set version = '1.3.4' %}
{% set posix = 'm2-' if win else '' %}
{% set native = 'm2w64-' if win else '' %}

package:
  name: r-castor
  version: {{ version|replace("-", "_") }}

source:
  url:
    - {{ cran_mirror }}/src/contrib/castor_{{ version }}.tar.gz
    - {{ cran_mirror }}/src/contrib/Archive/castor/castor_{{ version }}.tar.gz
  sha256: 64cb588ee574f2d1394a1cce7c2cc0be9cd3550c24ede2e2e709056413ec0b3e

build:
  merge_build_host: True  # [win]
  number: 1000
  rpaths:
    - lib/R/lib/
    - lib/

requirements:
  build:
    - {{ compiler('c') }}        # [not win]
    - {{ compiler('cxx') }}      # [not win]
    - {{native}}toolchain        # [win]
    - {{posix}}filesystem        # [win]
    - {{posix}}make
    - {{posix}}sed               # [win]
    - {{posix}}coreutils         # [win]
    - {{posix}}zip               # [win]
  host:
    - r-base
    - r-rcpp >=0.12.10
    - r-naturalsort
  run:
    - r-base
    - {{native}}gcc-libs         # [win]
    - r-rcpp >=0.12.10
    - r-naturalsort

test:
  commands:
    - $R -e "library('castor')"           # [not win]
    - "\"%R%\" -e \"library('castor')\""  # [win]

about:
  home: https://CRAN.R-project.org/package=castor
  license: GPL (>= 2)
  summary: 'Efficient tree manipulations for large phylogenies, including pruning, rerooting,
    calculation of most-recent common ancestors, calculating distances from the tree
    root and calculating pairwise distances. Calculation of phylogenetic signal and
    mean trait depth (trait conservatism), ancestral state reconstruction and hidden
    character prediction of discrete characters. Simulating and fitting models of trait
    evolution, and generating random trees using birth-death models. Dating trees, comparing
    two trees, and reading/writing trees to a file. Citation: Louca, Stilianos and Doebeli,
    Michael (2017) <doi:10.1093/bioinformatics/btx701>.'
  license_family: GPL3
  license_file: '{{ environ["PREFIX"] }}/lib/R/share/licenses/GPL-2'

extra:
  recipe-maintainers:
    - johanneskoester
    - bgruening
    - daler
    - jdblischak
    - cbrueffer
    - gavinmdouglas
    - dbast

# Package: castor
# Type: Package
# Title: Efficient Phylogenetics on Large Trees
# Version: 1.3.4
# Date: 2018-08-15
# Author: Stilianos Louca
# Maintainer: Stilianos Louca <louca@zoology.ubc.ca>
# Description: Efficient tree manipulations for large phylogenies, including pruning, rerooting, calculation of most-recent common ancestors, calculating distances from the tree root and calculating pairwise distances. Calculation of phylogenetic signal and mean trait depth (trait conservatism), ancestral state reconstruction and hidden character prediction of discrete characters. Simulating and fitting models of trait evolution, and generating random trees using birth-death models. Dating trees, comparing two trees, and reading/writing trees to a file. Citation: Louca, Stilianos and Doebeli, Michael (2017) <doi:10.1093/bioinformatics/btx701>.
# License: GPL (>= 2)
# Depends: Rcpp (>= 0.12.10)
# Imports: parallel, naturalsort, stats
# LinkingTo: Rcpp
# RoxygenNote: 6.0.1
# Suggests: testthat
# NeedsCompilation: yes
# Packaged: 2018-08-15 19:12:22 UTC; stilianoslouca
# Repository: CRAN
# Date/Publication: 2018-08-16 18:10:03 UTC
