travis:
  secure:
    BINSTAR_TOKEN: cW0Cnjrmw0t417rzbcn3/UtZe5pyPoPb8ALpmEaNwuGx6ls9UlVpoPVnS3JflmhvjPZyc1JuBy1ePbqLg/lQKeHdos1WDeo6Y5WRBkPLUV9Yqrrxegb0E2+gEupOhOj2CxA+4d1l4Li1vI9qIkaxchlA2Zu+vlE8xgdSanfY8rDaYpePEmIrajeWx3pnwVdM2sHW2up5tBgGmzmkodhcFb8iLvHObasvRV8nzemBOQed40FuwepxsdArfpdrW8zEGTG4isqVPeI1bOoYja4OjR/Vot+wdi+WRXN8F/v3eLv/XlrWQUw6U/i5b85RGFvle+paIphY4NA4Zph9VvBA+lGI7Ci5cELriI9pxCyrPdJHNucoZOeh4YasnSB7n/T9PH2zx9wu750dunTe3IG3Q7yJg445aoI64eDm6uUv8CxKpwhHe07zDO8fWvXuP1Rb7BZlOz+TJeiGwkmAG2duAi22eAuqpNbpF3dn2/IDgY3mI9arcD7x4iI/CdfOFhPZ27+KALkQeAmjfEkTw9PzhcgiWtb7PxF4Tlr3WnrH9WyYSAampiNtEn6oiYTeFxC6UaL18AvofoBRmWjwivrEz5gZEJ0U/A2goE7vpkaBy8VtrVp/qbDKAX9NjVEhp+zAEflz4rKoAzBQvt56B7dMj+pTbugysfkFMtL1QCULR6U=
appveyor:
  secure:
    BINSTAR_TOKEN: ipv/06DzgA7pzz2CIAtbPxZSsphDtF+JFyoWRnXkn3O8j7oRe3rzqj3LOoq2DZp4
