appveyor:
  secure: {BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1}
compiler_stack: comp7
max_py_ver: '37'
max_r_ver: '35'
travis:
  secure: {BINSTAR_TOKEN: bP4/sDJYMlz6PeQL6WMG/KYlnhsM+sW75icwf7XluJ6af18XmLSy0SNh7Qd7+RAsEiVxzL1fqfZMCjiA/y+jkrKGFq6ocHXo8wCQZBpgt3Ln7XySzecL0zPHyeuzilY+RqX/v7FU9qroPX3VVVBRf5PcLHRmReALsXaNzF8Yx7p09fhvc/85BOd4ngBNWH4idqW0BD2xLFz6LdKtvd8GdyPFJF/dRlLHGjoeCmkKMzF/uyW+TTr7Oy5YVpJzAWSPMF4keWp2i58M6WFPEfRC8S2d15X5I2yL2pjsm/rpTrc5rSy1hpZp+vgZBe8bxPhNTPZrvBb+cPHJV3kQKKq6pKiBnckNPjfOhCkJOCbZArMn5J9eA728Ca2wAbNu/CzWbfiZk/ELx7vY861YWkaUpJMTG20kYRpl0SKCsEAr/qtLFciUCUc/P1EY9TM5MnkFelbC8DJzHcNOHKag6R0uedkKkF4GFRfuDtL+7EcR42hTNw8daAPVCxPRNZoZmBSoo60IEmTXBfkQ5xS3X/dtPpGbpaBODYY1PSJbW0DZ/cOHH+yNaI+Y7ZB5gvIi1rgTxDkIS/msnGQs8vgRLsFpCrkofYveFpGtSc/SijcrQuWb6+3T911ncZxjpVv1rBNuqgSWbcuw5exA1UlhoJSoL1YO3M+Gl5Z/OExfFU7t/hY=}
